### ISSUE TITLE
replicate planner form

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-search-react#1]
You need to replicate this form: https://aishmittal.github.io/recipe-planner/#/ it can be done without styles on first time, just similar logic. if you need more detailed explanation - feel free to ask.

**Comment by rahuldcoder** [comment]
I am planning to remove bootstrap and instead using ant design because they already have a select box in them.

**Comment by rahuldcoder** [comment]
The UI of ant design is pretty professional

**Comment by atherdon** [comment]
i like you plan. get rid of bootstrap.

https://github.com/atherdon/groceristar/blob/master/client/public/images/logo46-facebook.png
or svg version
https://github.com/atherdon/groceristar/blob/master/client/public/images/logo46.svg

**Comment by atherdon** [comment]
@rahuldcoder can ant design be easily converted to like an app design? i mean used at react app? for some later stages...

**Comment by rahuldcoder** [comment]
Here is the first iteration of the application.Will attach logo today.
![screenshot from 2018-01-10 00-17-10](https://user-images.githubusercontent.com/18399319/34737496-5178c3ec-f59c-11e7-957c-f1d21683822f.png)

**Comment by rahuldcoder** [comment]
![screenshot from 2018-01-10 00-18-56](https://user-images.githubusercontent.com/18399319/34737750-05cc86f8-f59d-11e7-97fc-b806a3663831.png)

**Comment by atherdon** [comment]
Ok, I like it. it works and i'm happy with that. what do you think - we need to add some layouts in order to make it looks better? cause i'm not sure... i mean it must works - and i happy to have it like it looks right now.

**Comment by rahuldcoder** [comment]
![screenshot from 2018-01-10 00-19-06](https://user-images.githubusercontent.com/18399319/34737843-55f12d78-f59d-11e7-8b93-5ed62f3dda3c.png)

**Comment by rahuldcoder** [comment]
Lets first create the basic functioning and check that it works properly after that we can work on the looks and design.

**Comment by atherdon** [comment]
fully agree with you.

**Comment by rahuldcoder** [comment]
Ya and when it's functioning we can improve UI

**Comment by atherdon** [comment]
Ok, server is up and running.
you can check the data here: https://recipe-api-loopback.herokuapp.com/explorer
API sample: https://recipe-api-loopback.herokuapp.com/api/recipe

I'll migrate a data from my other database and buzz you, @rahuldcoder 
You can read more about queries here: #3

**Comment by atherdon** [comment]
i move my update into live server.
testing it right now. will update another tasks soon.

**Comment by atherdon** [comment]
#24

**Comment by atherdon** [comment]
@rahuldcoder i did it! really excited about it and sorry for taking this so long. hope you still interested to continue our development process.

i split recipe api into another piece, related just for search. So this server will work only for you and it require only models, that you need. i hope i'll be able to create a list with api urls that you'll be able to use and it'll be easy to test for us. if i'll take more time for me - you welcome to dig into loopback find method and explore it yourself. but i want to simplify it for you, so i'll try to finish it soon

back to details: 
repo: https://github.com/atherdon/recipe-search-api
heroku: https://loopback-recipe-search.herokuapp.com/explorer/#!/Recipe/Recipe_find

**Comment by atherdon** [comment]
i'm updating this part soon:

about queries here: #3
data structure #13
