### ISSUE TITLE
setup a rapi online server and make it available for outside requests

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-search-react#14]
we need to answer questions: 

- [x] 1. what i need to have in order to get data from database?
- [x] 2. do i need to login and receive token?
- [x] 3. can i make calls without tokens, just straight URL line and that it.
- [ ] 4. will Rahul be able to connect to server and test how logic is working?
- [x] 5. did i share all credentials and stuff and he can finish form submission?

#24

**Comment by rahuldcoder** [comment]
The current application has all the data stored in the state of the application. I have made state for every data that is submitted by the user and will use those variables to pass data to the API URL.Till now there is no login functionality associated with the application.

**Comment by atherdon** [comment]
ok, that is good.

Login is not enabled at api too. But it have login functionality by default, so yesterday when i login - it genereate a token at the end of URL. this is why i wrote this here. so maybe we'll need to send some kind of information before submit - in order to get response with token. not sure but we'll find it out soon
