### ISSUE TITLE
submit handler

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-search-react#45]
_will you be able to create a form submission to this api?
as told you before - don't have exact name for method that will apply for all filters, so just include backend urls with .env file as we did on your repository._

**Comment by chauhannishith** [comment]
I think we don't need two boxes for same entry, i mean to say if user has selected all products in haveingredients then we can assume that we can omit others. Similar is the case for other fields

**Comment by atherdon** [comment]
not agree.
I can forgot something and it'll be in the recipe.
assume that i'm searching for "chicken"(allowed ingredient).
but i don't want to find spicy and hot, so i add "curry" & "chilli papper"(disallowed ingredients).
at results page i'll have more better search results. so i think maybe we should change the form layout(or flow how user to fill that form) - but i think "-" sometime is more important the plus for results for this case

**Comment by atherdon** [comment]
But! maybe we can find a components, that will be a standalone one select,
but we'll be able to add their search results to "allowed" and
"dissallowed"?


On 25-May-2018 at 10:44 AM, chauhannishith wrote:


I think we don't need two boxes for same entry, i mean to say if user has
selected all products in haveingredients then we can assume that we can
omit others. Similar is the case for other fields

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-392015091>,
or mute the thread

**Comment by chauhannishith** [comment]
I understand what you are trying to say, it will take some time to understand and make the call

**Comment by chauhannishith** [comment]
Do you have any api with a large number of recepies where i can test these cases?

**Comment by atherdon** [comment]
we have a small api server. but maybe it's a good idea to connect to some
free recipe apis that we have on market.
hold on. i think i have what you need in my notes.


On 25-May-2018 at 01:43 PM, chauhannishith wrote:


Do you have any api with a large number of recepies where i can test these
cases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-392061830>,
or mute the thread

**Comment by chauhannishith** [comment]
> assume that i'm searching for "chicken"(allowed ingredient).
> but i don't want to find spicy and hot, so i add "curry" & "chilli papper"(disallowed ingredients).

i can tell that this functionality will need much more code than what initially was there, if we have to fetch the ingredients dynamically from an api rather than a static file

**Comment by atherdon** [comment]
yep, this will be one of our next tasks for this project. but for now - as
this is just a static form - static arrays working fine too. but yep, for
calling api - we'll need to have ids.


On 25-May-2018 at 01:52 PM, chauhannishith wrote:


assume that i'm searching for "chicken"(allowed ingredient).
but i don't want to find spicy and hot, so i add "curry" & "chilli
papper"(disallowed ingredients).

i can tell that this functionality will need much more code than what
initially was there, if we have to fetch the ingredients dynamically from
an api rather than a static file

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-392064684>,
or mute the thread

**Comment by chauhannishith** [comment]
I will try to find some solution to the select boxes as right now it feels like they will just go into deadlock if one is dependent on other as one item when selected in one box will have to be disabled for the other and i am confused that how will it happen without refresh

**Comment by atherdon** [comment]
good idea. i like it!


On 25-May-2018 at 02:17 PM, chauhannishith wrote:


I will try to find some solution to the select boxes as right now it feels
like they will just go into deadlock if one is dependent on other as one
item when selected in one box will have to be disabled for the other and i
am confused that how will it happen without refresh

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-392072395>,
or mute the thread

**Comment by chauhannishith** [comment]
Do you want to continue with antd only? I know it looks cool and in some ways might be better but it just seems like normal select would be better and also the size of code will be less

**Comment by atherdon** [comment]
but it wouldn't have an autocomplete functionality, right?
in this case - i'm ok with andt. if you want - mention Rahul to this topic
and if he have time - maybe he'll be able to advice you


On 26-May-2018 at 10:30 AM, chauhannishith wrote:


Do you want to continue with antd only? I know it looks cool and in some
ways might be better but it just seems like normal select would be better
and also the size of code will be less

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-392252499>,
or mute the thread

**Comment by chauhannishith** [comment]
Ok i will try it as it is and will tell if it is worth it or not

**Comment by atherdon** [comment]
Thanks! yep, we should try and understand if it fits to our main process


On 26-May-2018 at 10:44 AM, chauhannishith wrote:


Ok i will try it as it is and will tell if it is worth it or not

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-392253149>,
or mute the thread

**Comment by atherdon** [comment]
Btw, quick note. i think we should have some form validation. What do you think? maybe you know some component for it? i google formsy, but never use it. to be honest- i'm a bit sick of forms. build them a lot. so don't want personally dig into in deeply

**Comment by atherdon** [comment]
#37 #40

**Comment by atherdon** [comment]
@chauhannishith i made this article for you: https://medium.com/groceristar/companies-with-recipe-apis-e9f29a64389c hope it helps

**Comment by chauhannishith** [comment]
Ok. I think i understand a bit what you want to do. Will send you a message when i setup a test call to confirm if i am on the right track.(though i still don't understand the purpose of holidays)

**Comment by atherdon** [comment]
holidays is maybe the less important field. but a lot of websites use it,
so... Usually it used few times in year.
For example - "Best recipes for 4th July" or "Christmas pie". we trying to
work on server side of search form, and before holiday was a separated
table. but we decided to combine all this fields(selects) into Attributes
table. so when we have: +I1+I2+I3-I4+A1+C1(include is a plus, exclude is
minus, I = Ingredient, A = Allergy, etc) we'll send only id`s into loopack.
so i think this will save some of your times.
But that search api is not finished. if you with - i can send you a code
repo, to take a look


On 02-Jun-2018 at 12:54 AM, chauhannishith wrote:


Ok. I think i understand a bit what you want to do. Will send you a message
when i setup a test call to confirm if i am on the right track.(though i
still don't understand the purpose of holidays)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-394044143>,
or mute the thread

**Comment by chauhannishith** [comment]
I am currently going with EDAMAM, trying with static data, if that works then transferring to selected data should not take much time

**Comment by atherdon** [comment]
good to know! btw, i hope soon we'll finish our apis, so edamam will be
just a biggest competitor :) we'll have ingredients + nutritions data(5000
rows) imported. will test in June i assume


On 02-Jun-2018 at 04:36 AM, chauhannishith wrote:


I am currently going with EDAMAM, trying with static data, if that works
then transferring to selected data should not take much time

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-394057681>,
or mute the thread

**Comment by chauhannishith** [comment]
The test call is working but i can't find any example of how they need the query string format, can you find it when you wake up?
i tried this but seems like this doesnt work

> excluded: ["chicken",banan","apple"]
or

> excluded: "excluded=chicken&excluded=banana"

**Comment by chauhannishith** [comment]
What do you want me to do in this? Only fetch data or like have a display component with 10 lists(links to full recipe) and prev and next buttons

**Comment by atherdon** [comment]
you mean in search results?
let's display some raw data. like we did with form fields - just showing text.

pagination is a cool idea, but not sure that we should do it at this moment.
In other repositories I also have some un-finished components, related to displayin recipe data, so maybe we'll use it a bit later. if you want - you can show pagination component from antd, but please not bind it right now, ok?

**Comment by chauhannishith** [comment]
ok i will just fetch the data and display the recipe names for now

**Comment by atherdon** [comment]
good choice! can you create a separated task where we can discuss how we
can represent a search results?


On 03-Jun-2018 at 05:52 AM, chauhannishith wrote:


ok i will just fetch the data and display the recipe names for now

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-394139104>,
or mute the thread

**Comment by chauhannishith** [comment]
Sorry the internet is not working properly today, will have to do it tomorrow only

**Comment by atherdon** [comment]
it's ok, not a problem. maybe it will give me some time and review your
prev changes :)


On 03-Jun-2018 at 05:57 AM, chauhannishith wrote:


Sorry the internet is not working properly today, will have to do it
tomorrow only

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-394139277>,
or mute the thread

**Comment by chauhannishith** [comment]
![image](https://user-images.githubusercontent.com/29725515/41024784-cb7e1952-698d-11e8-8f5c-07303e172dde.png)

It will be helpful if you can tell me whats wrong with the last commit

**Comment by atherdon** [comment]
does it work right now? i saw that you've add a header to axious configuration...

**Comment by atherdon** [comment]
in order to represent error i should pick some other autocomplete fields,
right?


On 07-Jun-2018 at 01:22 AM, chauhannishith wrote:


No, it doesn't work. Only ingredients work properly, others give this error

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-395262917>,
or mute the thread

**Comment by chauhannishith** [comment]
Yes but with atleast one ingredient

**Comment by atherdon** [comment]
will grab some coffee and will check it deeply

**Comment by chauhannishith** [comment]
select one ingredient and one allergy and it will show you even in the netlify

**Comment by atherdon** [comment]
i tried option which you show me at screenshot. hold on, will try at
netlify instance


On 07-Jun-2018 at 08:34 AM, chauhannishith wrote:


select one ingredient and one allergy and it will show you even in the
netlify

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-395339051>,
or mute the thread

**Comment by chauhannishith** [comment]
we have only permits of 5 hits per minute so that might be the reason you didn't get any

**Comment by atherdon** [comment]
maybe. did we send 1 request for each form element?


On 07-Jun-2018 at 11:03 AM, chauhannishith wrote:


we have only permits of 5 hits per minute so that might be the reason you
didn't get any

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-395381320>,
or mute the thread

**Comment by chauhannishith** [comment]
no, we are sending only one request for all form data not a single element
btw did you get that error?

**Comment by atherdon** [comment]
Should i press search? i tried few times, tried to overload server. will
try a different browsers right now


On 07-Jun-2018 at 11:22 AM, chauhannishith wrote:


no, we are sending only one request for all form data not a single element
btw did you get that error?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-395385896>,
or mute the thread

**Comment by atherdon** [comment]
can you check how much items came for ingredients select? i assume this is
the most fat part of data that we fetch from that server....


On 07-Jun-2018 at 11:22 AM, chauhannishith wrote:


no, we are sending only one request for all form data not a single element
btw did you get that error?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-395385896>,
or mute the thread

**Comment by chauhannishith** [comment]
Yes you have to hit search recipies button
The error will be displayed in console

**Comment by atherdon** [comment]
when i hit search i just got a blank page at netlify. hold on will make a few more attempts. if you wish i can create a video about how it looks on my side. can do it for both - local and netlify versions

**Comment by atherdon** [comment]
ohh, just refresh as beast and got it at local version. exploring rigth now

**Comment by atherdon** [comment]
yeah i think we just hit a daily number of requests. maybe for debuggin reasons we should fetch some static data like ingredients and save them as json - while we're testing it?

**Comment by atherdon** [comment]
But why this error appeared only at submit... i mean if we're fetching data each time when i refresh page - it's strange to have restrictions only when we send `q` query... maybe they just didn't have all of options, that our form provide? maybe they didn't have exclude attributes...

Case#1
When I pick only chicken it's works well. 
Case#2 
When i pick chicken, tuna - it works too.

Case#3 when i pick chicken, tuna, Cheese - it' give me the same error

I didn't refresh page for each of this case...

---
When i refresh page and pick logical ingredients
Case#4 Broccoli, Tomato, oil - it works fine.

maybe they just haven't recipe with that cases? so it's like a 'No results' response?

**Comment by atherdon** [comment]
Yep, i suppose this error related to not-logical data, that we put in our form. So it's like - No results.
Case#5 i pick `Peanut Butter` and pick `Peanut-free` allegy and it give me an error too.

**Comment by atherdon** [comment]
Btw, you did a great job with sending one request for fetching data for select options!
When i was junior - my project lead was angry when i send 64 requests instead of 8 :)

**Comment by chauhannishith** [comment]
> can you check how much items came for ingredients select? i assume this is
> the most fat part of data that we fetch from that server....

they haven't given any method by which we can fetch the ingredients, they have only given the list of allergies and diets which they have


> yeah i think we just hit a daily number of requests

it is 5 requests/ min so we have to just wait a minute

**Comment by chauhannishith** [comment]
> yeah i think we just hit a daily number of requests. maybe for debuggin reasons we should fetch some static data like ingredients and save them as json - while we're testing it?

static will most probably work fine might be possible better than this but this looks more like real life scenario where user will fetch data over the web

**Comment by chauhannishith** [comment]
> maybe they just haven't recipe with that cases? so it's like a 'No results' response?

i assume this might be possible but i even tried a static request and that too failed, they probably might have given an error response to handle failure

**Comment by atherdon** [comment]
ok i think it's can be a two same issues in one time - 
first of all they might didn't have ingredients that we're picking, 
second is related to limitation of a free account and maybe we just need to try an ingredients that can be in one recipe. 

---
usually, i test food projects with chicken or salad options. because it's a simple cases. 
for more complex cases - when you want to check intersections, like receive recipes with chicken(like soup) and chicken salad - we'll need to go to the main website - search few recipes and use them as test cases

>> have given an error response to handle failure
it'll be sad if they don't cover errors. we like have it covered(loopback did it for basic methods) in our recipe-search-api

**Comment by chauhannishith** [comment]
i had spent atleast two hours yesterday trying different combinations and it worked with balanced diet but not others so i assume it might be because of free acount

**Comment by atherdon** [comment]
yeah i think so. but it's good that we're tried to connect our form to
separated API. it's good for testing on separated service. i think soon
we'll switch to our server, so it'll be more easy to understand - if'll get
errors. because you'll be able to grab long URL - put it on your browser
and see an actual json response


On 07-Jun-2018 at 12:32 PM, chauhannishith wrote:


i had spent atleast two hours yesterday trying different combinations and
it worked with balanced diet but not others so i assume it might be because
of free acount

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/45#issuecomment-395403490>,
or mute the thread
