### ISSUE TITLE
Can you make build and create a repository release with attaching zip file of html files?

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-search-react#6]
For sure when things will be done. just want to review how the form looks.

**Comment by rahuldcoder** [comment]
Ok just need to complete some select box and there is actually no need for the zip file. Just clone the repo and go in folder and run npm install
After complete download of all the files do npm start and the react app will run on ur local server.
Sending only the html files won't work.

**Comment by atherdon** [comment]
So do you mean that i must have react installed, right? i mean `npm install && run` will install packages and setup a create react app project. 

But is there any ways to have some sort of build thing? I'm a novice in react, you know...

So my main concerns is:
we have a recipe-api server and frontend part will be done with react. but how we can merge this stuff in order to run at one place but split logic: not mess in main repository that related to server only...
if my message not clear - i'll explain it more.
maybe i look to something like that: https://github.com/recallfx/todo-react-loopback

So at server folder, we have all complex things.
at client folder we have index.html and react stuff, i assume that was built before.

**Comment by atherdon** [comment]
@rahuldcoder maybe this is what i plan to have before: https://www.youtube.com/watch?v=M_PaFaIf6d8

**Comment by atherdon** [comment]
let's postpone this for now. But if you can create a release - it'll be awesome. @rahuldcoder

**Comment by atherdon** [comment]
#25
