### ISSUE TITLE
can you create a release for a current code state?

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-search-react#60]
i think we're ready and this will be an interesting task for you.
inside release please briefly explain what we did here and what we have right now

**Comment by chauhannishith** [comment]
don't know how that works but will try

**Comment by atherdon** [comment]
yep, it was my idea - to teach you how to do it


On 13-Jun-2018 at 04:46 AM, chauhannishith wrote:


don't know how that works but will try

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-search-react/issues/60#issuecomment-396812080>,
or mute the thread
