### ISSUE TITLE
401 at edamam api calls

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-search-react#66]
# Description/Steps to reproduce

Note: I occasionally get the "401 Unauthorised" response for the search requests. Once it starts, it doesn't fix itself until a page refresh.

# Expected result

# Additional information

**Comment by chauhannishith** [comment]
We can only do 2 requests in one minute so thats why it is giving that error, there were lots of emails related to limit exceeded so that is the reason for this

**Comment by atherdon** [comment]
then solved

**Comment by Luke-Robinett** [comment]
I can't seem to get a post request to work for this API using the $.AJAX method. I also keep getting an unauthorized error. Below is the code I'm using. The app ID and API key I'm trying to use is the same I'm successfully using for the recipe search API. Can anyone tell me why the following code doesn't work? Below the code I'll paste the error I get from the Chrome console. Thanks.

`    var queryUrl = "https://api.edamam.com/api/nutrition-details?app_id=" + appID + "&app_key=" + apiKey;
    $.ajax({
        url: queryUrl,
        method: "POST",
        contentType: "application/json",
        data: {
            "title": "pie",
            "ingr": [ "Apples", "cream cheese", "cherries" ]
        }
    }).then(function (response) {
        console.log(response);
    });
`

Console error:
jquery-3.4.1.js:9837 OPTIONS https://api.edamam.com/api/nutrition-details?app_id=599eeff6&app_key=9ba899b… 401 (Unauthorized)
Error
index.html:1 Access to XMLHttpRequest at 'https://api.edamam.com/api/nutrition-details?app_id=599eeff6&app_key=9ba899b…' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by atherdon** [comment]
i'm not sure if this code working with edamam correctly. it's not finished
yet

>
